use crate::{
    domain::runtime::{BrowserTabInfo, CookieInfo},
    error::AppError,
};
use chromiumoxide::cdp::browser_protocol::network::Cookie;
use chromiumoxide::Browser;
use futures::StreamExt;
use std::time::Duration;

pub fn probe_debug_ready(debug_port: i32) -> bool {
    if debug_port <= 0 {
        return false;
    }
    let url = format!("http://127.0.0.1:{debug_port}/json/version");
    reqwest::blocking::Client::builder()
        .timeout(Duration::from_millis(600))
        .build()
        .and_then(|client| client.get(url).send())
        .map(|resp| resp.status().is_success())
        .unwrap_or(false)
}

pub fn get_cookies(debug_port: i32) -> Result<Vec<CookieInfo>, AppError> {
    run_cdp(debug_port, |browser| async move {
        let cookies = browser.get_cookies().await?;
        let result = cookies.into_iter().map(map_cookie).collect();
        Ok(result)
    })
}

pub fn clear_cookies(debug_port: i32) -> Result<(), AppError> {
    run_cdp(debug_port, |browser| async move {
        browser.clear_cookies().await?;
        Ok(())
    })
}

pub fn export_cookies(debug_port: i32) -> Result<String, AppError> {
    let cookies = get_cookies(debug_port)?;
    Ok(export_netscape_cookies(&cookies))
}

pub fn list_tabs(debug_port: i32) -> Result<Vec<BrowserTabInfo>, AppError> {
    run_cdp(debug_port, |mut browser| async move {
        let targets = browser.fetch_targets().await?;
        let tabs = targets
            .into_iter()
            .map(|target| BrowserTabInfo {
                target_id: target.target_id.as_ref().to_string(),
                target_type: target.r#type,
                title: target.title,
                url: target.url,
                attached: target.attached,
            })
            .collect();
        Ok(tabs)
    })
}

fn run_cdp<T, Fut, F>(debug_port: i32, f: F) -> Result<T, AppError>
where
    F: FnOnce(Browser) -> Fut,
    Fut: std::future::Future<Output = Result<T, chromiumoxide::error::CdpError>>,
{
    if debug_port <= 0 {
        return Err(AppError::validation("invalid debug port"));
    }

    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .worker_threads(2)
        .build()
        .map_err(|err| AppError::other(format!("failed to create cdp runtime: {err}")))?;

    runtime.block_on(async move {
        let endpoint = format!("http://127.0.0.1:{debug_port}");
        let (browser, mut handler) = Browser::connect(endpoint).await?;
        let handle = tokio::spawn(async move {
            while let Some(next) = handler.next().await {
                if next.is_err() {
                    break;
                }
            }
        });

        let result = f(browser).await;
        handle.abort();
        result.map_err(AppError::from)
    })
}

fn map_cookie(cookie: Cookie) -> CookieInfo {
    CookieInfo {
        name: cookie.name,
        value: cookie.value,
        domain: cookie.domain,
        path: cookie.path,
        expires: cookie.expires,
        http_only: cookie.http_only,
        secure: cookie.secure,
        same_site: cookie
            .same_site
            .map(|value| value.as_ref().to_string())
            .unwrap_or_default(),
    }
}

fn export_netscape_cookies(cookies: &[CookieInfo]) -> String {
    let mut out = String::from("# Netscape HTTP Cookie File\n# Generated by Yubai\n\n");
    for cookie in cookies {
        let include_subdomains = if cookie.domain.starts_with('.') {
            "TRUE"
        } else {
            "FALSE"
        };
        let secure = if cookie.secure { "TRUE" } else { "FALSE" };
        let expires = if cookie.expires > 0.0 {
            cookie.expires as i64
        } else {
            0
        };
        out.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            cookie.domain,
            include_subdomains,
            cookie.path,
            secure,
            expires,
            cookie.name,
            cookie.value
        ));
    }
    out
}
