mod app;
mod commands;
pub mod domain;
mod error;
mod infra;
mod services;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    app::bootstrap::build()
        .invoke_handler(tauri::generate_handler![
            commands::dashboard::dashboard_stats_get,
            commands::dashboard::dashboard_workbench_get,
            commands::dashboard::app_config_get,
            commands::automation::automation_state_get,
            commands::automation::automation_settings_save,
            commands::automation::automation_runtime_install,
            commands::automation::automation_runtime_self_check,
            commands::automation::automation_script_list,
            commands::automation::automation_script_create,
            commands::automation::automation_script_update,
            commands::automation::automation_script_delete,
            commands::automation::automation_script_run_list,
            commands::automation::automation_script_run,
            commands::automation::automation_script_run_cancel,
            commands::launch_api::launch_api_config_get,
            commands::launch_api::launch_api_start,
            commands::launch_api::launch_api_stop,
            commands::settings::browser_settings_get,
            commands::settings::browser_settings_save,
            commands::settings::mihomo_download,
            commands::settings::app_logs_get,
            commands::settings::app_logs_clear,
            commands::browser::profile::browser_profile_list,
            commands::browser::profile::browser_profile_create,
            commands::browser::profile::browser_profile_update,
            commands::browser::profile::browser_profile_delete,
            commands::browser::core::browser_core_list,
            commands::browser::core::browser_core_save,
            commands::browser::core::browser_core_delete,
            commands::browser::core::browser_core_validate,
            commands::browser::core::browser_core_extended_info,
            commands::browser::core::browser_core_scan_local,
            commands::browser::core::browser_core_detect_system,
            commands::browser::core::browser_core_register_system,
            commands::browser::core::browser_core_download_options,
            commands::browser::core::browser_core_download,
            commands::proxy::browser_proxy_list,
            commands::proxy::browser_proxy_save,
            commands::proxy::browser_proxy_delete,
            commands::proxy::browser_proxy_fetch_clash_by_url,
            commands::proxy::browser_proxy_import_text,
            commands::proxy::browser_proxy_test,
            commands::proxy::browser_proxy_batch_test,
            commands::proxy::browser_proxy_ip_health,
            commands::proxy::browser_proxy_refresh_subscription,
            commands::proxy::browser_proxy_list_by_source,
            commands::browser::group::browser_group_list,
            commands::browser::group::browser_group_save,
            commands::browser::group::browser_group_delete,
            commands::browser::group::browser_group_move_profiles,
            commands::bookmark::bookmark_list,
            commands::bookmark::bookmark_save,
            commands::bookmark::bookmark_reset,
            commands::bookmark::bookmark_sync_to_profiles,
            commands::browser::snapshot::browser_snapshot_list,
            commands::browser::snapshot::browser_snapshot_create,
            commands::browser::snapshot::browser_snapshot_restore,
            commands::browser::snapshot::browser_snapshot_delete,
            commands::browser::runtime::browser_get_cookies,
            commands::browser::runtime::browser_clear_cookies,
            commands::browser::runtime::browser_export_cookies,
            commands::browser::runtime::browser_tabs_list,
            commands::browser::runtime::browser_instance_status,
            commands::browser::runtime::browser_instance_start,
            commands::browser::runtime::browser_instance_stop,
            commands::backup::backup_manifest_template,
            commands::backup::backup_export_package,
            commands::backup::backup_import_package,
            commands::user::user_config_get,
            commands::user::user_config_save,
            commands::file::file_resolve_path,
            commands::file::file_exists,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
